// GENERATED by tools/gen_dialog.py — DO NOT EDIT BY HAND.
// Regenerate: python3 tools/gen_dialog.py
#ifndef DIALOG_DATA_H_
#define DIALOG_DATA_H_
#include "SemesterState.h"
#include <string_view>
#include <cstddef>

namespace nccu::dialog {

// C++17: no std::span. lines is a pointer + count into a
// per-entry constexpr string_view array below.
struct Entry {
    std::string_view npcId;
    SemesterState    state;
    int              subState;
    const std::string_view* lines;
    int              lineCount;
    int              karmaDelta;
    std::string_view setsFlag;   // "" = none
    bool             flagValue;
};

inline constexpr std::string_view kL0[] = { "三月初，加退選系統的伺服器再次撐不住了。", "綜院 1 樓的傘架前，只剩你剛才存放的透明傘——", "不對，連那把也不見了。", "外面的雨，似乎打算整個學期都沒有停的意思。" };
inline constexpr std::string_view kL1[] = { "欸，加退選也沒搶到嗎？", "我有個管道，必修可以幫你喬一下。", "當然，小忙而已——你看我剛從商院面試回來，", "順手幫我把一樓傘架的那把透明傘帶上來就好。", "我借的嘛，不是偷的，放心。" };
inline constexpr std::string_view kL2[] = { "喔，那算了啦，反正那把傘也不重要。", "加退選的事你自己去排隊吧，祝你好運。", "（轉身繼續滑手機，不再理你）" };
inline constexpr std::string_view kL3[] = { "太好了，這才是好學弟／妹嘛。", "加退選的事你就放心，我先幫你記著喔。", "（剛接過傘，傘骨突然發出奇怪的嗡嗡聲）", "……這傘，好像不是我的？", "（走廊遠端傳來急促的腳步聲）" };
inline constexpr std::string_view kL4[] = { "加退選系統崩了，你也沒搶到課嗎？", "行政大樓的助教那邊有紙本備案名單，", "不是官方說的，但有時候會通融。", "去試試看吧，反正淋雨也不是辦法。" };
inline constexpr std::string_view kL5[] = { "你說傘不見了？", "我剛才在 1 樓有看到一個穿西裝的學長，", "拿著把透明傘往集英樓方向走。", "你快去追，我繼續讀書了。" };
inline constexpr std::string_view kL6[] = { "找到了嗎？", "有些事就算跑斷腿也追不回來。", "不過你有去試，這樣就夠了。" };
inline constexpr std::string_view kL7[] = { "同學，加退選截止了，現在不受理。", "如果要申訴，填表、等通知，流程就這樣。", "……你說你的傘不見了？", "這不是我的業務範圍。", "（低頭繼續整理資料夾）" };
inline constexpr std::string_view kL8[] = { "謝謝你……那份表格要是不見我真的完了。", "說來慚愧，傘架的事我其實有注意到一點。", "集英樓 2 樓有個穿西裝的，你去問問吧。", "加退選的事我幫你備註一下，不保證，但試試看。" };
inline constexpr std::string_view kL9[] = { "等一下——", "那把傘，是某教授放在傘架的私人物品。", "你是怎麼拿到的？", "（助教丟下資料夾，往你的方向走過來）" };
inline constexpr std::string_view kL10[] = { "哎呀同學，淋這麼濕進來喔！", "加退選又在搶了是嗎，年年都這樣。", "要喝什麼？熱的比較好，暖暖身子。", "今天下雨我多備了一點貨，你慢慢看。" };
inline constexpr std::string_view kL11[] = { "傘？你問對地方了。", "就這一把，螢光綠的，醜是醜了點，", "但保證沒人拿錯——顏色這麼衝，", "貨架上最後一把，特價八十塊。", "要不要？不買也沒關係，但雨還在下喔。" };
inline constexpr std::string_view kL12[] = { "聰明！醜有醜的好處啦。", "從今以後你的傘就是全校最好辨認的。", "哈，下次加退選記得早點來搶，加油喔。" };
inline constexpr std::string_view kL13[] = { "……我的傘不見了。", "加退選剛結束，出來傘架就空的。", "有人看到一個西裝的學長，", "拿著透明傘往集英樓方向跑。", "你也是被偷的嗎？" };
inline constexpr std::string_view kL14[] = { "真的？謝謝你……", "那把傘是我媽買給我的，有點重要。", "你要小心那個學長，他看起來很會說話。" };
inline constexpr std::string_view kL15[] = { "（那個同學看了你一眼，又低下頭）", "……沒人在乎嗎。", "（雨在外頭繼續打）" };
inline constexpr std::string_view kL16[] = { "四月中旬。期中考週第一天。", "圖書館閱覽室的燈比任何教室都亮，", "卻有一種讓人睡著的安靜。", "你離開座位，走向傘架——", "架上只剩一張紙。", "上面密密麻麻寫滿了微積分公式。", "你的傘，又不見了。" };
inline constexpr std::string_view kL17[] = { "學霸的眼神終於回神了一點。", "傘換回來了。這次，更換是你。", "雨依舊沒有停，但你出來了。", "字卡：「幾週後，操場的廣播聲傳進了圖書館……」" };
inline constexpr std::string_view kL18[] = { "（手機收進口袋，眼神掃了你一下）", "喔。是你。", "期中加油，我先走了。", "（轉身，步伐不快不慢）" };
inline constexpr std::string_view kL19[] = { "哎，你也在嗎？期中週還在跑腿哦。", "我見習錄取了，今天去行政大樓辦手續。", "對了，你在找什麼嗎？臉色不太好。", "圖書館三樓靠窗有個讀書讀到不動的學弟，", "剛才看他撐著傘走去羅馬廣場了。" };
inline constexpr std::string_view kL20[] = { "……有事嗎？", "我這邊有約，不方便。", "（視線往遠處飄，不看你）" };
inline constexpr std::string_view kL21[] = { "……嗯？你說什麼。", "（視線從筆記本移開一公分，沒有完全抬頭）", "傘？我有傘。", "哪裡拿的……就，那邊。傘架吧。", "（繼續低頭看書，嘴裡念著公式）" };
inline constexpr std::string_view kL22[] = { "（第一頁頁眉寫著：「別打擾，看完就還」）", "（第二頁空白處：「期末準備就從現在開始」）", "（第三頁最後一行：「附近傘架的傘都是我的了」）", "（最後一行被劃掉了，旁邊小字：「搞什麼，我又當機了」）" };
inline constexpr std::string_view kL23[] = { "（你把飲料放到他面前）", "（他低頭看了三秒，拿起來喝了一口）", "……甜的。有點噁。", "（他眨了幾下眼睛，抬起頭來）", "你是……圖書館那個？", "那把傘是你的？我以為是路人放的。", "（他的眼睛沒有焦距，嘴裡在念公式）", "……斯托克斯定理……微分算子……", "（完全沒有反應）", "現在跟他說話沒有用。也許需要什麼東西喚醒他。" };
inline constexpr std::string_view kL24[] = { "那個……算我欠你一個。", "筆記你幫我撿回來了嗎？", "（接過筆記，翻了一下）好，沒丟。", "傘的事你沒有很兇——這個我記得。", "（站起來，拉了拉外套）走了，圖書館還有位子。" };
inline constexpr std::string_view kL25[] = { "期中考週，大家加油。", "圖書館人多，座位要早點去佔。", "（資料夾裡掉出一張 A4，他彎腰撿起來）", "……（盯著那張紙半秒，又快步往前走）" };
inline constexpr std::string_view kL26[] = { "是你。上次申請書的事，謝謝。", "（眼鏡推了推）期中加油。", "這週三樓有個讀書讀到不動的學生，", "你有事可以去問問他，他在那裡很久了。", "（轉身，步伐沒有停）" };
inline constexpr std::string_view kL27[] = { "（助教突然停下來，轉頭）", "等一下——你就是那個同學。", "那把教授的傘，最後到哪去了。", "（語氣比 Ch1 稍低，眼鏡框後面的眼睛盯著你）", "你自己知道就好。我記著這件事。" };
inline constexpr std::string_view kL28[] = { "哎呀，進來，外面雨大。", "今天備的都是熱的，護眼貼也有。", "考試週大家那個臉色哦……", "我也不知道說什麼好，反正先喝熱的。" };
inline constexpr std::string_view kL29[] = { "拿好，剛沖的，慢慢喝。", "圖書館那棟最近很奇怪，", "我看到有人撐著傘在外面站雨裡——", "年輕人啊，讀書讀到這樣也不行啦。" };
inline constexpr std::string_view kL30[] = { "你這個同學哦，淋這麼濕來——", "先站著，我去拿條抹布。", "（塞了個護眼貼過來）拿著，不用錢。", "沒事的，快去找傘，別在外面晃。" };
inline constexpr std::string_view kL31[] = { "你也在圖書館備考嗎。", "（抬頭看了看玩家的手，沒有傘）", "你還在找啊？", "（低頭繼續看書，但嘴角動了一下）" };
inline constexpr std::string_view kL32[] = { "……沒關係，我已經習慣了。", "借了朋友的傘，還她的時候她說不用急。", "（停了一下）你比我執著——" };
inline constexpr std::string_view kL33[] = { "（手指貼在嘴唇前，壓低聲音）", "那個……三樓靠窗的，", "讀書讀到快睡著那位。", "他撿了什麼東西就出去了——", "剛才有個學生問我，說他掉了幾頁筆記，", "你去各樓層找找，他筆記到處飄的。" };
inline constexpr std::string_view kL34[] = { "（看了一眼你手上的筆記頁）都找到了？", "那個同學剛才出去了，往廣場方向。", "雨還在下，你如果要追——", "（遞過一個折好的折疊傘，上面貼著「管理室備用」的貼紙）", "這個先拿著，外面太大雨，不能不管你。" };
inline constexpr std::string_view kL35[] = { "5 月下旬，校慶運動會，操場難得人滿為患。", "你把傘掛在鐵絲網上，湊過去看大隊接力。", "第三棒還沒跑完——你轉頭，傘不見了。", "在這片嘉年華的泥濘裡，你決定再找一次。" };
inline constexpr std::string_view kL36[] = { "傘被你從道具箱底部救出來了。", "彩帶還纏著，但傘還是你的傘。", "字卡：「幾週後，期末考的氣壓壓下來了……」" };
inline constexpr std::string_view kL37[] = { "哎，你也來看運動會？我說你這個人。", "我今天認識了三個系的同學，這才叫校慶。", "你的傘不見了？……這我有耳聞，等一下。", "（看了一眼啦啦隊方向）那邊，A 系攤位，去問看看。", "喔，你也來啊。", "我正在認識人，你有事嗎？", "傘？不知道，我沒注意。" };
inline constexpr std::string_view kL38[] = { "A 系烤香腸那攤，他們的道具箱一直被借來借去。", "我沒多問——但你要找情報，先從那邊進。", "算是還你 Ch1 的人情啦，別說我沒良心。" };
inline constexpr std::string_view kL39[] = { "啦啦隊的道具箱？喔，那個我有看到有人搬。", "你的傘在裡面啊——那幫人不是故意的啦。", "去後台跟他們說你要拿東西，他們不會攔人。" };
inline constexpr std::string_view kL40[] = { "那種場合我不去，吵。你怎麼跑來圖書館？", "傘又不見了？……（沉默三秒）你真的很不順。", "我聽說有人把道具借去體育館——去那邊問。" };
inline constexpr std::string_view kL41[] = { "那種場合我不去，吵。", "你要找什麼……我現在在讀書。", "（低頭，沒再抬起來）去問別人。" };
inline constexpr std::string_view kL42[] = { "同學，活動出席登記要填表。", "（沒有看你，繼續寫字）填完放這邊。", "同學，活動出席登記要填表。", "今天人多，流程請照規定來，謝謝。", "（眼鏡滑下來，習慣性地用中指推上去）快一點。" };
inline constexpr std::string_view kL43[] = { "後台？那不是一般同學可以進去的地方。", "要進去的話要有負責人同意——我不是負責人。", "……啦啦隊的帶頭是四維堂那邊的，你去問他們。" };
inline constexpr std::string_view kL44[] = { "……你是 Ch1 那個幫我找申請書的同學對吧。", "後台那邊有個道具箱，負責人是我認識的學長。", "我傳了訊息給他，你直接去說是來拿傘的就好。" };
inline constexpr std::string_view kL45[] = { "哎呀，你也來看運動會？好久沒有停課了。", "我賣這個——加油棒、彩帶、防水噴霧。", "今天早上就快賣完了，學生還蠻有熱情的。", "（碎念）就是那個大聲公一直在我耳邊——煩死了。" };
inline constexpr std::string_view kL46[] = { "啦啦隊啊！四維堂那邊的，很認真在練。", "我看他們早上搬了一堆道具去體育館後台。", "傘當道具……也不是沒見過啦，這群人有創意。", "你的傘被拿走了喔？去後台說清楚，他們不壞的。" };
inline constexpr std::string_view kL47[] = { "哦！找到了啊？好，這樣就安心了。", "下次不要把傘掛在鐵絲網上，那邊什麼都會不見。", "要買點什麼嗎？防水噴霧噴一下，傘比較耐用。" };
inline constexpr std::string_view kL48[] = { "……你還沒找到。", "（沉默，整理了一下攤上的飾品）", "沒關係。" };
inline constexpr std::string_view kL49[] = { "……你也是被偷的嗎？", "操場這邊很多人的傘都不見了。", "（低頭，沒有再說什麼）" };
inline constexpr std::string_view kL50[] = { "要買烤香腸嗎？三十塊一根，現烤的。", "不過我有個麻煩——隔壁 B 系跟我借了我的衛生紙。", "你去幫我要回來，我送你一根怎麼樣？" };
inline constexpr std::string_view kL51[] = { "謝謝你！拿去，趁熱吃——哦，你要拿去換東西？", "B 系那個大聲公啊，他跟我借過。你去就好了。" };
inline constexpr std::string_view kL52[] = { "加油！加——啊，我喉嚨快不行了。", "你要借大聲公？不借，我還要用。", "……除非你有吃的，我從早站到現在了。", "那是香腸！？給我！我從早站到現在了！" };
inline constexpr std::string_view kL53[] = { "（接過香腸，眼睛亮了）你救了我。", "大聲公拿去，C 系學姊那邊你去說我借你的。", "她在四維道攤位那邊，你認得出來——她最高。" };
inline constexpr std::string_view kL54[] = { "你來買東西嗎？現在還有剩幾樣。", "大聲公？不給，我們啦啦隊要用的。", "有什麼可以拿來換嗎？說來聽聽。", "（眼睛一亮）這個……B 系的那個？", "你是打哪來的，等等，先說清楚。" };
inline constexpr std::string_view kL55[] = { "好，我知道你要找什麼了。", "啦啦隊今早拿了一把傘當表演道具。", "就在體育館後台，道具箱的第三個，從左邊算。", "去快一點，他們下午還要用那個空間彩排。" };
inline constexpr std::string_view kL56[] = { "6 月 8 日，期末考週第一天。", "集英樓便利商店燈很亮，你買了泡麵出來。", "你轉頭的那一秒——傘又不見了。", "磅礡大雨，視線昏暗，整座山下校園是你的最後一關。", "這一次，所有的事都要結束了。" };
inline constexpr std::string_view kL57[] = { "哎，你找傘？我有看到。", "我認識的管道這次用不上——", "但這次我是真的知道人在哪裡。", "你要不要先聽我說？" };
inline constexpr std::string_view kL58[] = { "……你這個人，幫的人比我多很多。", "我 Ch1 那次，其實傘也不是正版的。", "我只是不想你去找錯地方。", "（停頓）研究大樓，走廊最底的那間研究室。", "助教，三天沒睡，拿了你的傘，他不是故意的。", "你體諒他一下——我欠你的情就算還了。" };
inline constexpr std::string_view kL59[] = { "……我有看到一個人抱著傘往研究大樓跑。", "你最近做的事，我有點耳聞。", "算了，你自己去查，研究大樓方向。", "管道不是給每個人用的——你知道的。" };
inline constexpr std::string_view kL60[] = { "你還在找傘？", "（沉默兩秒）這學期……你蠻拚的。", "我沒有你的情報，我只是來考試的。", "（低頭，閉眼）去找阿姨或學長——他們消息比我多。" };
inline constexpr std::string_view kL61[] = { "……Ch2 的事，你沒有很兇。", "你讓我把書讀完，我記得。", "研究大樓——有人抱著傘往最底那間跑。", "我不確定，但你值得知道這個。" };
inline constexpr std::string_view kL62[] = { "你要找傘？", "我不知道。去問別人。", "（閉眼，不再說話）" };
inline constexpr std::string_view kL63[] = { "同學，這裡是研究大樓，", "期末考期間不對外開放，你——", "（低頭看了一眼考卷）……等一下。", "（看到自己夾的傘，停頓）", "這把……不是我的傘？" };
inline constexpr std::string_view kL64[] = { "……Ch1 那個幫我找申請書的同學對吧。", "（眼神停了一秒）這把傘，我拿到你的了。", "三天了，我以為是辦公室的備用傘。", "我沒有藉口——流程就是這樣，不能出包，", "但這次是我出包了。", "（把傘遞出來）你的。" };
inline constexpr std::string_view kL65[] = { "……等一下，你就是 Ch2 那個。", "（語氣變緊）那把傘，教授那邊——", "我查過了。那把傘你是從哪來的？", "（抿嘴）算了，現在說這個沒用了。", "但你知道，這件事我記著。" };
inline constexpr std::string_view kL66[] = { "期末考週了，每年都這樣——", "大家眼圈越來越黑，我的備品換了三次。", "要什麼你說，我幫你找。" };
inline constexpr std::string_view kL67[] = { "你傘又不見了哦？這學期第幾次了。", "我這邊沒賣傘——但集英樓便利商店有一把，", "放在最底層很久了，螢光綠的，醜到沒人買。", "（碎念）我說老闆，那個顏色是什麼眼光……", "反正，你有急用就去看看——保證沒人跟你搶。" };
inline constexpr std::string_view kL68[] = { "哦，不買啊，也好——那個顏色確實很難看。", "你去找找，傘總是會在某個地方的。", "找到記得來買個咖啡暖身子，考試加油哦。" };
inline constexpr std::string_view kL69[] = { "（看到你走近，沒有躲）", "傘找到了。謝謝你有記得。", "（停頓）這學期……你跑了很多路。", "我媽買的傘，沒有壞，很好。" };
inline constexpr std::string_view kL70[] = { "（沒有看你，繼續低著頭）", "……你來了。", "沒關係。", "（低頭，拉了一下帽子，沒有再說什麼）" };

inline constexpr Entry kEntries[] = {
    { "__scene__", SemesterState::Chapter1_AddDrop, 0, kL0, 4, 0, "", false },
    { "suit_senior", SemesterState::Chapter1_AddDrop, 0, kL1, 5, 0, "", false },
    { "suit_senior", SemesterState::Chapter1_AddDrop, 1, kL2, 3, 0, "", false },
    { "suit_senior", SemesterState::Chapter1_AddDrop, 2, kL3, 5, -5, "Flag_ScoldedSenior", false },
    { "bookworm", SemesterState::Chapter1_AddDrop, 0, kL4, 4, 0, "", false },
    { "bookworm", SemesterState::Chapter1_AddDrop, 1, kL5, 4, 3, "", false },
    { "bookworm", SemesterState::Chapter1_AddDrop, 2, kL6, 3, 0, "", false },
    { "ta", SemesterState::Chapter1_AddDrop, 0, kL7, 5, 0, "", false },
    { "ta", SemesterState::Chapter1_AddDrop, 1, kL8, 4, 5, "Flag_HelpedTA_Ch1", true },
    { "ta", SemesterState::Chapter1_AddDrop, 2, kL9, 4, -15, "", false },
    { "shop_auntie", SemesterState::Chapter1_AddDrop, 0, kL10, 4, 0, "", false },
    { "shop_auntie", SemesterState::Chapter1_AddDrop, 1, kL11, 5, 0, "", false },
    { "shop_auntie", SemesterState::Chapter1_AddDrop, 2, kL12, 3, 0, "Flag_BoughtUglyUmbrella", true },
    { "victim", SemesterState::Chapter1_AddDrop, 0, kL13, 5, 0, "", false },
    { "victim", SemesterState::Chapter1_AddDrop, 1, kL14, 3, 5, "Flag_PromisedVictim", true },
    { "victim", SemesterState::Chapter1_AddDrop, 2, kL15, 3, -3, "", false },
    { "__scene__", SemesterState::Chapter2_Midterms, 0, kL16, 7, 0, "", false },
    { "__scene__", SemesterState::Chapter2_Midterms, 2, kL17, 4, 0, "", false },
    { "suit_senior", SemesterState::Chapter2_Midterms, 0, kL18, 4, 0, "", false },
    { "suit_senior", SemesterState::Chapter2_Midterms, 1, kL19, 5, 3, "Flag_HelpedSenior", true },
    { "suit_senior", SemesterState::Chapter2_Midterms, 2, kL20, 3, -3, "", false },
    { "bookworm", SemesterState::Chapter2_Midterms, 0, kL21, 5, 0, "Flag_TookCursedUmbrella", true },
    { "bookworm", SemesterState::Chapter2_Midterms, 1, kL22, 4, 3, "", false },
    { "bookworm", SemesterState::Chapter2_Midterms, 2, kL23, 10, 0, "", false },
    { "bookworm", SemesterState::Chapter2_Midterms, 3, kL24, 5, 5, "", false },
    { "ta", SemesterState::Chapter2_Midterms, 0, kL25, 4, 0, "", false },
    { "ta", SemesterState::Chapter2_Midterms, 1, kL26, 5, 0, "Flag_HelpedTA_Ch1", true },
    { "ta", SemesterState::Chapter2_Midterms, 2, kL27, 5, -10, "", false },
    { "shop_auntie", SemesterState::Chapter2_Midterms, 0, kL28, 4, 0, "", false },
    { "shop_auntie", SemesterState::Chapter2_Midterms, 1, kL29, 4, 0, "Flag_TookCursedUmbrella", true },
    { "shop_auntie", SemesterState::Chapter2_Midterms, 2, kL30, 4, 0, "", false },
    { "victim", SemesterState::Chapter2_Midterms, 0, kL31, 4, 0, "Flag_PromisedVictim", true },
    { "victim", SemesterState::Chapter2_Midterms, 1, kL32, 3, 0, "Flag_BoughtUglyUmbrella", true },
    { "librarian", SemesterState::Chapter2_Midterms, 0, kL33, 6, 0, "", false },
    { "librarian", SemesterState::Chapter2_Midterms, 1, kL34, 5, 0, "", false },
    { "__scene__", SemesterState::Chapter3_SportsDay, 0, kL35, 4, 0, "", false },
    { "__scene__", SemesterState::Chapter3_SportsDay, 3, kL36, 3, 0, "", false },
    { "suit_senior", SemesterState::Chapter3_SportsDay, 0, kL37, 7, 0, "Flag_HelpedSenior", true },
    { "suit_senior", SemesterState::Chapter3_SportsDay, 1, kL38, 3, 0, "", false },
    { "suit_senior", SemesterState::Chapter3_SportsDay, 2, kL39, 3, 0, "", false },
    { "bookworm", SemesterState::Chapter3_SportsDay, 0, kL40, 3, 0, "", false },
    { "bookworm", SemesterState::Chapter3_SportsDay, 1, kL41, 3, 0, "", false },
    { "ta", SemesterState::Chapter3_SportsDay, 0, kL42, 5, 0, "", false },
    { "ta", SemesterState::Chapter3_SportsDay, 1, kL43, 3, 0, "", false },
    { "ta", SemesterState::Chapter3_SportsDay, 2, kL44, 3, 0, "", false },
    { "shop_auntie", SemesterState::Chapter3_SportsDay, 0, kL45, 4, 0, "", false },
    { "shop_auntie", SemesterState::Chapter3_SportsDay, 1, kL46, 4, 0, "", false },
    { "shop_auntie", SemesterState::Chapter3_SportsDay, 2, kL47, 3, 0, "", false },
    { "victim", SemesterState::Chapter3_SportsDay, 0, kL48, 3, 0, "", false },
    { "victim", SemesterState::Chapter3_SportsDay, 1, kL49, 3, 0, "", false },
    { "vendor_a", SemesterState::Chapter3_SportsDay, 0, kL50, 3, 0, "", false },
    { "vendor_a", SemesterState::Chapter3_SportsDay, 1, kL51, 2, 0, "", false },
    { "vendor_b", SemesterState::Chapter3_SportsDay, 0, kL52, 4, 0, "", false },
    { "vendor_b", SemesterState::Chapter3_SportsDay, 1, kL53, 3, 0, "", false },
    { "senior_c", SemesterState::Chapter3_SportsDay, 0, kL54, 5, 0, "", false },
    { "senior_c", SemesterState::Chapter3_SportsDay, 1, kL55, 4, 0, "", false },
    { "__scene__", SemesterState::Chapter4_Finals, 0, kL56, 5, 0, "", false },
    { "suit_senior", SemesterState::Chapter4_Finals, 0, kL57, 4, 0, "Flag_HelpedSenior", false },
    { "suit_senior", SemesterState::Chapter4_Finals, 1, kL58, 6, 0, "", false },
    { "suit_senior", SemesterState::Chapter4_Finals, 2, kL59, 4, 0, "", false },
    { "bookworm", SemesterState::Chapter4_Finals, 0, kL60, 4, 0, "", false },
    { "bookworm", SemesterState::Chapter4_Finals, 1, kL61, 4, 0, "Flag_BookwormRecovered", true },
    { "bookworm", SemesterState::Chapter4_Finals, 2, kL62, 3, 0, "", false },
    { "ta", SemesterState::Chapter4_Finals, 0, kL63, 5, 0, "", false },
    { "ta", SemesterState::Chapter4_Finals, 1, kL64, 6, 0, "Flag_HelpedTA_Ch1", true },
    { "ta", SemesterState::Chapter4_Finals, 2, kL65, 5, 0, "Flag_HelpedTA_Ch1", true },
    { "shop_auntie", SemesterState::Chapter4_Finals, 0, kL66, 3, 0, "Flag_BoughtCoffeeForAuntie_Ch1", true },
    { "shop_auntie", SemesterState::Chapter4_Finals, 1, kL67, 5, 0, "", false },
    { "shop_auntie", SemesterState::Chapter4_Finals, 2, kL68, 3, 0, "", false },
    { "victim", SemesterState::Chapter4_Finals, 0, kL69, 4, 0, "Flag_PromisedVictim", false },
    { "victim", SemesterState::Chapter4_Finals, 1, kL70, 4, 0, "Flag_PromisedVictim", true },
};

inline constexpr std::size_t kEntryCount = 71;

struct EntryRange {
    const Entry* b;
    const Entry* e;
    const Entry* begin() const { return b; }
    const Entry* end()   const { return e; }
};
inline EntryRange All() {
    return { kEntries, kEntries + kEntryCount };
}

} // namespace nccu::dialog
#endif // DIALOG_DATA_H_
